name: Run CI
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.2
      - name: Install bundler
        run: bundle install
      - name: Create Service Account Credential file
        run: |
          echo "$SERVICE_CREDENTIALS" > service_account_credential.json.b64
          base64 -d -i service_account_credential.json.b64 > service_account_credential.json
          bundle exec fastlane run validate_play_store_json_key json_key:service_account_credential.json
        env:
          SERVICE_CREDENTIALS: ${{ secrets.SERVICE_CREDENTIALS }}
      - name: Submit
        run: |
          echo "$KEYSTORE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > keystore.jks
          gradle :app:assembleRelease
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          MapboxAccessToken: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          MapboxDownloadsToken: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
